### ISSUE TITLE
API version out of date

### ISSUE THREAD

**Issue by EllyArd** [thorwe/teamspeak-plugin-ducker#3]
If the API calls haven't changed significantly, can you please increment the version?

I know you haven't been around for awhile, but it's honestly a key feature of teamspeak for >20 people.

**Comment by TomTom39** [comment]
Yes please! We need that plugin. That's impossible to hear a whisper in 20 ppl channel during heavy fps battle... :( I will tip you

**Comment by thorwe** [comment]
Please find a beta update [here](https://github.com/thorwe/teamspeak-plugin-ducker/releases).

I only had the time for a quick test, so I'd be eager to hear if there're problems.
