### ISSUE TITLE
API version still outdated

### ISSUE THREAD

**Issue by TomTom39** [thorwe/teamspeak-plugin-ducker#4]
Please update Awesome Ducker Plugin for Api version 24.
![image](https://user-images.githubusercontent.com/74629869/99461042-50c29d80-2931-11eb-8d3f-671c9b3ada2e.png)

**Comment by thorwe** [comment]
Please find a beta update [here](https://github.com/thorwe/teamspeak-plugin-ducker/releases).

I only had the time for a quick test, so I'd be eager to hear if there're problems.
